<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    "button.return_to_index" => "Volver a la lista",
    "button.view" => "Mostrar",
    "button.edit" => "Editar",
    "button.delete" => "Borrar",
    "button.create_and_edit" => "Crear y editar",
    "button.create_and_list" => "Crear y regresar al listado",
    "button.create_and_create" => "Crear y agregar otro",
    "button.update_and_edit" => "Actualizar",
    "button.update_and_list" => "Actualizar y cerrar",
    "label.actions" => "Acciones",
    "label.add_new" => "Crear {0}",
    "button.add_new" => "Agregar nuevo",
    "label.editing" => 'Editando',
    "button.save" => "Actualizar",
    "button.logout" => "Cerrar sesión",
    "flash.update.success" => "El elemento {0} '{1}' fue actualizado satisfactoriamente.",
    "flash.update.error" => "Elemento {0} '{1}' se no se pudo actualizarse.",
    "flash.create.success" => "Elemento {0} '{1}' creado satisfactoriamente.",
    "flash.create.error" => "Ocurrio un error al crear el elemento {0}",
    "flash.delete.success" => "Elemento {0} '{1}' su eliminado satisfactoriamente.",
    "flash.delete.error" => "Elemento {0} '{1}' pudo ser eliminado.",
    "alert.success" => "Bien",
    "alert.info" => "Información",
    "alert.warning" => "Cuidado",
    "alert.danger" => "Ha ocurrido un error",
    "question.delete.confirm" => "Seguro que desea eliminar el item '{0}'?",
];
